name: pushToMain

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      # - run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Next.js App
        run: npm run build

      - name: Start Next.js App in Background
        run: npm run start & # Start the server in the background
        env:
          NODE_ENV: test
          PORT: 3000
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30